### ISSUE TITLE
findMin function does not support no data values

### ISSUE THREAD

**Issue by adehecq** [DHI-GRAS/qgis-temporal-profile#19]
It seems like the functions findMin and findMax in plottingtool.py do not support no data values. This means that when clicking on a pixel where at least one the bands is set to NoData, a Python error is raised (see trace below), and the min/max values of the profile are not automatically updated.

**Comment by adehecq** [comment]
Traceback (most recent call last):
  File "/home/adehecq/.local/share/QGIS/QGIS3/profiles/default/python/plugins/temporalprofiletool/temporalprofileplugin.py", line 176, in leftClicked
    self.doubleClicked(point)
  File "/home/adehecq/.local/share/QGIS/QGIS3/profiles/default/python/plugins/temporalprofiletool/temporalprofileplugin.py", line 181, in doubleClicked
    self.doprofile.calculatePointProfile(point, self.mdl, self.plotlibrary)
  File "/home/adehecq/.local/share/QGIS/QGIS3/profiles/default/python/plugins/temporalprofiletool/tools/doprofile.py", line 118, in calculatePointProfile
    PlottingTool().reScalePlot(self.dockwidget, self.profiles, model, library)
  File "/home/adehecq/.local/share/QGIS/QGIS3/profiles/default/python/plugins/temporalprofiletool/tools/plottingtool.py", line 193, in reScalePlot
    wdg.sbMaxVal.setValue(maximumValue)
  File "/home/adehecq/.local/share/QGIS/QGIS3/profiles/default/python/plugins/temporalprofiletool/tools/plottingtool.py", line 167, in findMin
    return floor(minVal) if abs(minVal) > 1 else minVal
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

**Comment by j08lue** [comment]
You do not seem to be using the latest version of the plugin. Can you please update and try again? The current code for `findMin` and `findMax` looks like this:

https://github.com/DHI-GRAS/qgis-temporal-profile/blob/85a0756551562f9839339a88d2ce28f5d19d6ccf/tools/plottingtool.py#L157-L169

And I see no way you could get a `None` comparison anywhere there.

**Comment by radosuav** [comment]
@adehecq the relevant code change might not have been included in a published plugin but only in the git repository. Could you try with 2.0.1 release for QGIS 3 which you can get from [GitHub](https://github.com/DHI-GRAS/qgis-temporal-profile/releases/tag/2.0.1) and soon from the QGIS plugin repository.

**Comment by adehecq** [comment]
Sorry for the late reply. I just realized GitHub was still sending notifications to my previous email address which has been deleted...
Anyway, I just tried installing version 2.0.1 and it solved my issues. Thanks!
