### ISSUE TITLE
x-axis steps: from string

### ISSUE THREAD

**Issue by Matthew-J-Payne** [DHI-GRAS/qgis-temporal-profile#27]
Thanks for this great plugin and your work on it!

When I try to load a string of dates from a .txt file, I get the following trace:

```
Traceback (most recent call last):
  File "C:\Users/matth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\temporalprofiletool\temporalprofileplugin.py", line 274, in changeXAxisLabeling
    self.doprofile.xAxisSteps = [ float(x) for x in self.doprofile.xAxisSteps ]
  File "C:\Users/matth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\temporalprofiletool\temporalprofileplugin.py", line 274, in 
    self.doprofile.xAxisSteps = [ float(x) for x in self.doprofile.xAxisSteps ]
ValueError: could not convert string to float: '"2017-05-22'
```
My guess is that the formatting of the dates.txt (attached) is causing the matplotlib error?

For future users, could you include an example .txt string of accepted dates on your repo?

thanks and all the best,
Matt
[dates.txt](https://github.com/DHI-GRAS/qgis-temporal-profile/files/10057784/dates.txt)

**Comment by Matthew-J-Payne** [comment]
Forgot to say - I'm using version 2.1.2

**Comment by radosuav** [comment]
Thanks for kind words :) 

Did you try removing the quotation marks and spaces from the text file? Let me know and if it still does not work then I'll have a look in the code.

**Comment by Matthew-J-Payne** [comment]
No problem : )

Just now, I have tried removing quotation marks and spaces but returns the same error:

```
Traceback (most recent call last):
  File "C:\Users/matth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\temporalprofiletool\temporalprofileplugin.py", line 274, in changeXAxisLabeling
    self.doprofile.xAxisSteps = [ float(x) for x in self.doprofile.xAxisSteps ]
  File "C:\Users/matth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\temporalprofiletool\temporalprofileplugin.py", line 274, in 
    self.doprofile.xAxisSteps = [ float(x) for x in self.doprofile.xAxisSteps ]
ValueError: could not convert string to float: '2017-05-22'
```

Does matplotlib not expect the date format that I am using?

**Comment by jgrn307** [comment]
I'm getting the same issue with this file for an AVIRIS.  If I select-all, copy/paste right out of this file into the String it works fine, but loading the file directly throws this error:

An error has occurred while executing Python code: 

AttributeError: type object 'QgsMessageBar' has no attribute 'WARNING' 
Traceback (most recent call last):
  File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\temporalprofiletool\temporalprofileplugin.py", line 274, in changeXAxisLabeling
    self.doprofile.xAxisSteps = [ float(x) for x in self.doprofile.xAxisSteps ]
  File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\temporalprofiletool\temporalprofileplugin.py", line 274, in 
    self.doprofile.xAxisSteps = [ float(x) for x in self.doprofile.xAxisSteps ]
ValueError: could not convert string to float: '\ufeff365.92981000000003'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\temporalprofiletool\temporalprofileplugin.py", line 280, in changeXAxisLabeling
    QgsMessageBar.WARNING, 5)
AttributeError: type object 'QgsMessageBar' has no attribute 'WARNING'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.1-Lima Lima, 4a078ecf63 

Python Path:
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python
C:/Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.1\apps\grass\grass83\etc\python
C:\Users\gears\Documents
C:\Program Files\QGIS 3.32.1\bin\python39.zip
C:\PROGRA~1\QGIS33~1.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib
C:\Program Files\QGIS 3.32.1\bin
C:\PROGRA~1\QGIS33~1.1\apps\Python39
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/gears/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\gears\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms

[aviris_wavelengths.txt](https://github.com/DHI-GRAS/qgis-temporal-profile/files/12209935/aviris_wavelengths.txt)

**Comment by radosuav** [comment]
@jgrn307 your issue is a bit different. It's because you have unicode \ufeff (byte order) character at the very beginning of the file. When you copy and paste then probably this character gets stripped.

@Matthew-J-Payne the issue was not with matplotlib but with the way the plugin was trying to interpret the string. 

Both the issues should now be fixed in the https://github.com/DHI-GRAS/qgis-temporal-profile/tree/x_axis_steps branch. Could you please test and let me know how it goes. If you are on Windows then you'll need to replace the code in `C:\Users\<user_name>\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\temporalprofiletool`

**Comment by radosuav** [comment]
I merged the branch ([6b0439c](https://github.com/DHI-GRAS/qgis-temporal-profile/commit/6b0439c6d90fd0fd2649bb973c159b911da3351c)) and submitted a new version of the plugin to QGIS plugin repository. If the issue is still there then please reopen.
